services:
  sanchezdns:
    image: mizle/sanchezdns:latest
    container_name: sanchezdns
    platform: linux/amd64
    ports:
      - 3000:80
    environment:
      - AWS_REQUEST_CHECKSUM_CALCULATION=WHEN_REQUIRED
      - AWS_RESPONSE_CHECKSUM_VALIDATION=WHEN_REQUIRED
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
      s3:
        condition: service_started
      s3-create-bucket:
        condition: service_completed_successfully
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  s3:
    image: rustfs/rustfs:latest
    container_name: s3
    restart: unless-stopped
    environment:
      - RUSTFS_ACCESS_KEY=${FS_USERNAME}
      - RUSTFS_SECRET_KEY=${FS_PASSWORD}
      - RUSTFS_CONSOLE_ENABLE=true
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3_data:/data
      - s3_logs:/logs
    command: >
      --address :9000
      --console-enable
      /data

  s3-create-bucket:
    image: minio/mc:latest
    container_name: s3-create-bucket
    depends_on:
      - s3
    environment:
      - FS_USERNAME=${FS_USERNAME}
      - FS_PASSWORD=${FS_PASSWORD}
      - FS_BUCKET=${FS_BUCKET}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://s3:9000 $$FS_USERNAME $$FS_PASSWORD; do sleep 2; done;
      mc mb -p local/$$FS_BUCKET || true;
      mc anonymous set download local/$$FS_BUCKET || true;
      exit 0;
      "

volumes:
  mongo_data:
  redis_data:
  s3_data:
  s3_logs:
